### ISSUE TITLE
Rename base.Tree.climb() please

### ISSUE THREAD

**Issue by lukaszachy** [psss/fmf#1]
Tree structures are usually visualized from top to bottom, even wikipedia says that "Root: The top node in a tree". With that in mind name 'climb' is a bit confusing. Function is doing tree traversal.

Proposed name: traverse

**Comment by psss** [comment]
I was thinking about it a bit more and (after discussion with other guys) decided to keep it as it is. Climbing is used for both up and down and it's a bit shorter then `traverse` ;)

    Rock climbing is an activity in which participants climb up,
    down or across natural rock formations or artificial rock walls.

Sorry, Lukáš :)
