### ISSUE TITLE
make .cache location configurable

### ISSUE THREAD

**Issue by sopos** [psss/fmf#100]
It there is a concurrent run of fmf (using wow), there is quite high change of race condition in the cache.

This is connected to https://github.com/psss/tmt/issues/356

**Comment by sopos** [comment]
one instance
```
15:10:28 bwt-new: [ERROR] Failed to add TC#0597307 - /CoreOS/sudo/Configs/bz1626972-migrate-yum-dnf-configuration due issue with TMT Metadata: Error in loading fmf object from {u'url': u'git://pkgs.devel.redhat.com/tests/sudo', u'name': u'/Configs/bz1626972-migrate-yum-dnf-configuration'}. Raised exception was: Command 'git checkout -f master' returned non-zero exit status 1
```
another instance
```
15:10:35 bwt-new: [ERROR] Failed to add TC#0597307 - /CoreOS/sudo/Configs/bz1626972-migrate-yum-dnf-configuration due issue with TMT Metadata: Error in loading fmf object from {u'url': u'git://pkgs.devel.redhat.com/tests/sudo', u'name': u'/Configs/bz1626972-migrate-yum-dnf-configuration'}. Raised exception was: Command 'git checkout -f master' returned non-zero exit status 1
```
Note that the times are pretty close to each other.

**Comment by lukaszachy** [comment]
User / caller has no supported way how to specify _cache_ directory to mittigate concurrency issues until #96 is fixed (or even later if parallel runs are expected to lock themselfves a lot).

Possible workaround should be to monkeypatch `XDG_CACHE_HOME` variable
