### ISSUE TITLE
Skipping axes with CannotDecide makes boolean operations act nothing like boolean operations.

### ISSUE THREAD

**Issue by t184256** [psss/fmf#117]
```
>>> fmf.context.Context(package='pkg-1').matches('package <= pkg-2')
True
>>> fmf.context.Context(distro='fedora-33').matches('distro <= centos-7.7')
...
fmf.context.CannotDecide
>>> fmf.context.Context(package='pkg-1', distro='fedora-33').matches('package < pkg-2 and distro <= centos-7.7')
True
```

This is [documented](https://fmf.readthedocs.io/en/latest/context.html#syntax):
> Expression skipping
>    When a dimension or outcome of the operation is not defined, the expression is skipped over.

But it's absolutely counterintuitive.

Consequential weird things:
* `distro < rhel-8 and distro < fedora-33`: `True` for `fedora-32`, `False` for `fedora-99`
* `distro < rhel-8 or distro < fedora-33`: `True` for `fedora-32`, `False` for `fedora-99`

Counter-proposal:

`CannotDecide and True` = `True and CannotDecide` = `CannotDecide`
`CannotDecide and False` = `False and CannotDecide` = `False`
`CannotDecide or True` = `True or CannotDecide` = `True`
`CannotDecide or False` = `False or CannotDecide` = `CannotDecide`

**Comment by jscotka** [comment]
HI,
I can imagine, also some command line option what will do some tweaking of some default values.

I can imagine, some fallback syntax, eg.
when you will have e.g. `filter: X and Y or Z`, I can imagine some syntax like
 - `filter: X[True] and Y[False] or dist <= centos-8[False]`, what will use this default value if variable is not defined.
 - `filter: X:=True Y:=False dist:=centos-9 X and Y or dist <= centos-8` or this will assign some default value to variables if they are not defined, and then logic formulas will be same.


What will add very powerful tooling. and will be nice

**Comment by lukaszachy** [comment]
@jscotka Thanks for the idea, lets discuss it there and leave this issue just for CannotDecide problem
