### ISSUE TITLE
`fmf` shows something in empty directory

### ISSUE THREAD

**Issue by AloisMahdal** [psss/fmf#12]
(Note: this is just a quick feedback from exploration of fmf; IOW I haven't read all docs and might be wrong in what I expect.)

    @work:~/tmp/sandbox$ mkdir fmf-foo
    @work:~/tmp/sandbox$ cd fmf-foo/
    @work:~/tmp/sandbox/fmf-foo$ fmf
    fmf-foo
    @work:~/tmp/sandbox/fmf-foo$

README.md says this command should "List all metadata stored in the current directory", but obviously there's none, so why does it show anything?

**Comment by psss** [comment]
Good point! Agreed :)
