### ISSUE TITLE
fmf-0.15.2-1.el7: python36-fmf is missing in EPEL-7

### ISSUE THREAD

**Issue by jharuda** [psss/fmf#135]
It looks like the dependency `python36-fmf` is missing in EPEL-7.
There is the python2-fmf-0.15.2-1.el7.noarch.rpm package in EPEL-7.

It looks like the bug is introduced in fmf-0.15.2-1.el7 [1].
It worked in the release fmf-0.14-1.el7 [2].

How to reproduce in CentOS-7:
$ yum install -y epel-release
$ yum provides python*-fmf

[1] https://koji.fedoraproject.org/koji/buildinfo?buildID=1728458
[2] https://koji.fedoraproject.org/koji/buildinfo?buildID=1668354

**Comment by lukaszachy** [comment]
This was intentional change in 423dfdb81a2025 - fmf is now built only for the system version of python.
May I ask about your use case for this package?

**Comment by jharuda** [comment]
We use it in provision script when creating kvm instances.
https://pagure.io/standard-test-roles/blob/master/f/inventory/standard-inventory-qcow2

**Comment by lukaszachy** [comment]
Thank you. For now best will be to install it from pypi `pip3 install fmf` as there is no `python3-filelock` package in EPEL at the moment.

**Comment by jharuda** [comment]
OK. But please add it to EPEL-7 in the future.

**Comment by lukaszachy** [comment]
I'm afraid there are no resources to support other than system python.

**Comment by psss** [comment]
Yes, and because of the missing `python36-filelock` dependency we cannot build `python36-fmf` anymore. If you still need to use the package on `el7` we recommend to install the last build directly from koji:

    yum install -y https://kojipkgs.fedoraproject.org//packages/fmf/0.14/1.el7/noarch/python36-fmf-0.14-1.el7.noarch.rpm

Or use `pip` to fetch the latest code from the [pypi](https://pypi.org/project/fmf/) repository.
