### ISSUE TITLE
ref is trimmed into 8 char.

### ISSUE THREAD

**Issue by phracek** [psss/fmf#139]
My json request look like:

```json
{
  "api_key": "dbe42b09-cb4c-480a-b25e-51700cbd3656",
  "test": {"fmf": {
    "url": "<URL_WITH_FMF_REPO>",
    "ref": "refs/pull/449/head"
  }},
  "environments": [{
    "arch": "x86_64",
    "os": {"compose": "CentOS-7"},
    "variables": {
      "REPO_URL": "https://github.com/sclorg/s2i-python-container",
      "REPO_NAME": "s2i-python-container",
      "PR_NUMBER": "449",
      "OS": "fedora",
      "TEST_NAME": "test"
    }
  }]
}
```

when I call command   `curl <TESTING_FARM_URL>/requests --data @request.json --header "Content-Type: application/json"`

Then if fail with the error:
```json
"result":
       {"overall": "error",
         "summary": "Failed to checkout ref refs/pull/52/head: fatal: 'refs/pull/52/head' is not a commit and a branch 'refs/pul' cannot be created from it\n",
         "xunit": null},
```

**Comment by psss** [comment]
The [ref](https://fmf.readthedocs.io/en/latest/concept.html#identifiers) key should include branch, tag or commit specifying the desired git revision. This is used to perform a `git checkout` in the repository. For `refs/pull/449/head` the checkout does not work.

**Comment by phracek** [comment]
You are right, but pull/449/head does not work as well.
It looks like fetch is not called everytime https://github.com/psss/fmf/blob/6ffce891f75fd69af541393fed58b0c5026db459/fmf/utils.py#L748

**Comment by lukaszachy** [comment]
@phracek what is the git command sequence which will work for it? 
At the moment fmf does 1. git clone 2. git fetch, 3. git checkout. AFAIK there is no guarantee that PR's commit is part of the main repo (especially for forks) as github's hints to use pull from forked repo.

With that said I'm afraid this is NOTABUG and if I read this as a rfe to support PR/MR workflow it is CANTFIX :/

**Comment by phracek** [comment]
@lukaszachy After a deep analyze. I think, This is not a bug neither RFE. Propose of this issue was to checkout in FMF repo into specific PR, but It can be solved by many other ways.

Closing it.
