### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by psss** [psss/fmf#141]
I believe we have invested enough energy to keep the Python 2 backward compatibility and gave enough time for tools to migrate to Python 3. There are possibly still a few scripts which are using the old version but I think it's ok if we say there will be no more updates for `epel7` and state that `fmf` is supported for `rhel8+`, `centos8+` and all supported Fedora releases. Any objections or concerns? I think we should target this for `fmf-1.0`.

**Comment by psss** [comment]
@lukaszachy, @FrNecas, @jscotka, what do you say?

**Comment by lukaszachy** [comment]
I'm for dropping python2.
