### ISSUE TITLE
Allow deeper nesting from single .fmf file

### ISSUE THREAD

**Issue by jkrysl** [psss/fmf#17]
If you specify attributes on deeper layer than actual + 1, this gets interpreted as standalone leaf and does not get merged. To demonstrate this I created 2 entries that should get merged into one, as they appear to be on the same position in the tree. But the result is 2 different leaves, 'test -> test/directory' and 'test -> test -> directory' ('->' symbolizes branch of the tree).

```
[root@localhost test]# tree
.
├── main.fmf
└── test
    └── directory
        └── main.fmf

2 directories, 2 files

[root@localhost test]# fmf
test/test/directory
test: True
test/test/directory
test: True

[root@localhost test]# cat main.fmf              
/test/directory:
  test: True
[root@localhost test]# cat test/directory/main.fmf 
test: True
```

**Comment by psss** [comment]
Nice catch! Agreed that it would be nice & useful to be able to define a deeper virtual hierarchy on one line.
