### ISSUE TITLE
Is Python 2.7 supported?

### ISSUE THREAD

**Issue by clebergnu** [psss/fmf#21]
`setup.py` says so (and, doesn't even mention Python 3.x).  But, text/data/encoding issues exist when running on Python 2.7:

```
$ fmf > foo 
Traceback (most recent call last):
  File "/home/cleber/.local/bin/fmf", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/cleber/src/fmf/bin/fmf", line 35, in <module>
    fmf.cli.main()
  File "/home/cleber/src/fmf/fmf/cli.py", line 127, in main
    print(show, end="")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0160' in position 140: ordinal not in range(128)

$ git rev-parse HEAD
3d59b97b8beaa75035526fdf992530adef26f19a
```

**Comment by AloisMahdal** [comment]
Your use case works for me with `en_US.utf8`, on RHEL-6 with Python 2.6.  So it looks like one of those python/unicode problem.  What's your `locale`?

**Comment by AloisMahdal** [comment]
Nevermind, I found out it does not matter. Breaks even with my locale, **when** some UTF-8 is actually in main.fmf.

**Comment by AloisMahdal** [comment]
Full reproducer:

    echo 'description: Vypätá dcéra grófa Maxwella s IQ nižším ako kôň núti čeľaď hrýzť hŕbu jabĺk.' > main.fmf
    fmf > foo

On RHEL-6 w/ python 2.6:

    # echo 'description: Vypätá dcéra grófa Maxwella s IQ nižším ako kôň núti čeľaď hrýzť hŕbu jabĺk.' > main.fmf
    # fmf > foo
    Traceback (most recent call last):
      File "/usr/bin/fmf", line 35, in <module>
        fmf.cli.main()
      File "/usr/lib/python2.6/site-packages/fmf/cli.py", line 114, in main
        print(show)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 27: ordinal not in range(128)
    #

**Comment by psss** [comment]
Yes, currently supported python version are: 2.6, 2.7 and 3.6. I've updated `setup.py` accordingly in 569ba53.
