### ISSUE TITLE
root tree element should be first location of *.fmf file

### ISSUE THREAD

**Issue by jscotka** [psss/fmf#29]
Hi,
I think about using fmf command and how it deals with directories and root items.
dir structure like: `a/b/c/main.fmf` and first `main.fmf` is in `c` directory could produce structure like:
```
c/fist ....
c/second ...
```
and `root` item is `a/b`

and it could be invoked like 
```
fmf --brief .
fmf --brief a
fmf --brief a/b
fmf --brief `pwd`
```
and everytime it will produce same output what I see very beneficial for referencing, than now it is very dependent on invocation of command.

then I can imagine, that you have tests for beakerlib and you have two components like `bash` and `wget` and you checkout these gits locally, call `fmf` tool and it will produce consistent sructure not dependent on place of invocation.
imagine for example you have `~/git/wget` and `~/otherpath/git/bash` and invocation like `fmf ~` will produce output like 
```
wget/sanity
wget/second
bash/sanity
bash/regression
```

What do you think? maybe could be beneficial also  for merging trees
     Regards
     Honza

**Comment by psss** [comment]
Please, have a look at #26 where we discuss the special `.fmf` directory.

**Comment by jscotka** [comment]
We can close this.
