### ISSUE TITLE
Docs: fmf doesn't respect commands

### ISSUE THREAD

**Issue by Andrei-Stepanov** [psss/fmf#39]
Hi,

I am not sure if this is a bug, but cmdline tool doesn't recognise any command:

http://fmf.readthedocs.io/en/latest/overview.html

```
ls show
ls: cannot access show: No such file or directory
```

rpm -q fmf
fmf-0.4-1.el7.noarch

**Comment by AloisMahdal** [comment]
I believe command support has been added with *fmf-0.5*.

OTOH, above you seem to have just called *ls* with argument `show`, which is unrelated to fmf.

**Comment by Andrei-Stepanov** [comment]
```
fmf show  
 ERROR  Unable to walk through the 'show' directory.
```

**Comment by Andrei-Stepanov** [comment]
```
(venv)➜  standard-test-roles git:(master_copr_build) ✗ fmf show
 ERROR  Unable to walk through the 'show' directory.


(venv)➜  standard-test-roles git:(master_copr_build) ✗ which fmf    
~/tmp/venv/bin/fmf

(venv)➜  standard-test-roles git:(master_copr_build) ✗ pip list 
Package    Version
---------- -------
fmf        0.5.1  
pip        10.0.1 
PyYAML     3.12   
setuptools 0.9.8  


(venv)➜  standard-test-roles git:(master_copr_build) ✗ fmf ls   
 ERROR  Unable to walk through the 'ls' directory.

```

**Comment by jkrysl** [comment]
$ fmf show
/testing
test: 0151753773

$ cat .fmf/version
1

Please make sure you are on version 0.5 (commit 76cc950baec3c8e47725739df20c5154172a1150, now HEAD), the behaviour you are seeing seems like the old version, where there were no commands for fmf, just specifying the path.

**Comment by Andrei-Stepanov** [comment]
```
cat .fmf/version ~/.fmf/version 
1
1
```

```
✗ which fmf
~/tmp/venv/bin/fmf
```


```
strace fmf ls 2>&1 | head -n 1
execve("/home/astepano/tmp/venv/bin/fmf", ["fmf", "ls"], [/* 39 vars */]) = 0
```

**Comment by Andrei-Stepanov** [comment]
fmf        0.5.1  
installed from pip

**Comment by Andrei-Stepanov** [comment]
If I remove RPM package fmf it recognises commands. But it is real bug. Because it ignores virtualenv. Doesn't allow to use in production env.

**Comment by psss** [comment]
I'm not sure how the script can ignore virtual environment. It is just importing the python module in the standard way:

    import fmf.cli
    import fmf.base
    import fmf.utils

Is there any extra action or setup needed to make it working with virtualenv?

**Comment by Andrei-Stepanov** [comment]
I do not know.

```
In [1]: import fmf

In [2]: fmf??
Type:        module
String form: <module 'fmf' from '/home/astepano/tmp/venv/lib/python2.7/site-packages/fmf/__init__.pyc'>
File:        ~/tmp/venv/lib/python2.7/site-packages/fmf/__init__.py
Source:
""" Flexible Metadata Format """
```

Can you investigate this issue, or do you want me to take action ?

**Comment by Andrei-Stepanov** [comment]
Could you please try to reproduce this bug?
It is easy.

1. Have installed RPM
2. Initialise new python virtualenv.
3. Install the latest fmf in virtualenv.

**Comment by psss** [comment]
I believe this is caused by `fmf` being hashed by bash:

    > which fmf
    /tmp/fmf/bin/fmf

    > type fmf
    fmf is hashed (/usr/bin/fmf)

    > hash -l
    builtin hash -p /tmp/fmf/bin/pip pip
    builtin hash -p /usr/bin/fmf fmf
    builtin hash -p /usr/bin/vim vim

    > hash -r

    > fmf ls
    /download/test
    /download/requirements/no-clobber
    /download/requirements/server-response
    ...

Try to clean your hash using `hash -r`.

**Comment by Andrei-Stepanov** [comment]
I am using zsh.
When I use bash there is no such error.
Okay, it seems some inconsistency in shell.
