### ISSUE TITLE
Hangs up on: fmf ls

### ISSUE THREAD

**Issue by Andrei-Stepanov** [psss/fmf#40]
Hi,

fmf ls hangs up and runs forever.

```
(venv)➜  empty git:(master_copr_build) ✗ mkdir empty 
(venv)➜  empty git:(master_copr_build) ✗ cd empty 
(venv)➜  empty git:(master_copr_build) ✗ fmf ls
```

```
10734 astepano  20   0  170704  20588   2368 R 50.3  2.0   0:18.81 fmf                                                                                                                                        
```

**Comment by psss** [comment]
Sorry, I'm not able to reproduce this:

    psss@psss:/tmp> mkdir empty
    psss@psss:/tmp> cd empty/
    psss@psss:/tmp/empty> fmf ls
    ERROR  Unable to find tree root for '/tmp/empty'.

    psss@psss:/tmp/empty> source /tmp/fmf/bin/activate
    (fmf) psss@psss:/tmp/empty> which fmf
    /tmp/fmf/bin/fmf
    (fmf) psss@psss:/tmp/empty> type fmf
    fmf je /tmp/fmf/bin/fmf
    (fmf) psss@psss:/tmp/empty> fmf ls

    ERROR  Unable to find tree root for '/tmp/empty'.
    (fmf) psss@psss:/tmp/empty> 

Have you done any additional step?

**Comment by Andrei-Stepanov** [comment]
```
(venv)[astepano@centos7 empty]$ cd /tmp/
(venv)[astepano@centos7 tmp]$ mkdir empty
(venv)[astepano@centos7 tmp]$ fmf ls
 ERROR  Unable to find tree root for '/tmp'.
```


but if I use ~/tmp/empty it hangs up

**Comment by Andrei-Stepanov** [comment]
```
(venv)[astepano@centos7 empty]$ pwd
/home/astepano/tmp/empty

(venv)[astepano@centos7 empty]$ fmf ls --debug
 DEBUG  Coloring enabled (COLOR_AUTO)
 INFO  Root directory found: /home/astepano
 INFO  Format version detected: 1
 INFO  Walking through directory /home/astepano
```

Is this correct ?

**Comment by psss** [comment]
I think you have `.fmf` created in your home directory. This means `fmf` is trying to explore the whole home directory. Which may take a while. Do you possibly have any mounts there?

**Comment by psss** [comment]
The `.fmf` directory works similarly as `.git`. See:
http://fmf.readthedocs.io/en/latest/concept.html#tree

**Comment by Andrei-Stepanov** [comment]
Okay, then it seems as expected. Thank you for your help.
