### ISSUE TITLE
Fedora infra doesn't show Summary for RPM package

### ISSUE THREAD

**Issue by Andrei-Stepanov** [psss/fmf#44]
https://apps.fedoraproject.org/packages/fmf
https://apps.fedoraproject.org/packages/s/fmf

Both show: 

```
no summary in mdapi
```

**Comment by psss** [comment]
Filed a new issue in mdapi:
https://pagure.io/mdapi/issue/70

**Comment by psss** [comment]
This seems to be fixed. Both pages now correctly state "Flexible Metadata Format". Not sure what/where the problem was.
