### ISSUE TITLE
Syntax for test dependencies

### ISSUE THREAD

**Issue by mrc0mmand** [psss/fmf#53]
## Background

The Beakerlib metdatada file `Makefile` contains, among other things, fields `Requires` and `Rhts-Requires`, which hold test dependencies. This is a yet another important piece of information, which should be stored along with the test itself, however, in its current form (in Beakerlib) it's pretty inflexible, as there is no way to split such dependencies for multiple versions of a distribution, let alone for different distributions.

That said, this real-life example:
```bash
	@echo "Requires:        systemd yum-utils network-scripts" >> $(METADATA)
```

is pretty problematic, as:
* `yum-utils` has been replaced by `dnf-utils` on RHEL8, but there is no way to conditionally affect this during dependency resolution
* `yum-utils` may not be present on other distributions, so using these dependencies directly without any modifications is basically impossible
* etc.

This can be solved (and has been done so in many tests) by either placing both `yum-utils` and `dnf-utils` into the test dependencies and *hope* dnf/yum can handle it (and usually help it by using `--skip-broken`), or edit the test itself to do something like:

```bash
if rlIsRHEL "<=7"; then
    yum -q -y install yum-utils
else
    dnf -q -y install dnf-utils
fi
```

which is ugly, unportable, and in many cases even unstable.

## Proposals
As we're going to discuss this more in depth next week, I'll just dump here some ideas which can be used as a starting point.

### 1)  Re-using relevancy machinery to do dependency resolution as well
To make the dependency resolution more flexible, and in this case more *dynamic*, we could, theoretically, re-use part of the mechanism from relevancy resolution, as it already provides functionality necessary to resolve dependencies as well.

For example:
```yaml
example: |
    requires:
       - "distro >= f-22 | distro >= rhel-8: systemd dnf-utils cryptsetup"
       - "distro < f-21 | distro < rhel-8: systemd yum-utils cryptsetup"
```

The one of the disadvantages of this syntax is increased verbosity, as there is no way (at least known to me), to do something like `distro > f-22: dnf-utils; else: yum-utils`.

### 2) Sticking with *text-only* dependencies
On contrary to the first *solution*, this one is more *passive*, as it's the plain key-value mapping with a pre-defined distro format string.

```yaml
requires: |
    fedora-[12][01]:
        - systemd yum-utils
    fedora-[2-9].*:
        - systemd dnf-utils
```

However, this is really confusing and error-prone format (and I'm not even sure if it's a valid YAML).

**Comment by psss** [comment]
After discussing the issue in person we've agreed that the best solution for this use case seems to be to store `requires` and similar information needed for proper environment preparation in L2 metadata. I've created issue in Fedora CI Metadata project to define the `prepare` step so that @mrc0mmand can start real-life experimenting with this approach. I guess we can close this one, right?

**Comment by mrc0mmand** [comment]
Yep, thank you!
