### ISSUE TITLE
Allow free-form Python conditions from the command line

### ISSUE THREAD

**Issue by psss** [psss/fmf#55]
Sometimes it is necessary to investigate deeper structures of the data dictionary in order to perform the desired filtering. In addition to the `--filter` option we could also provide a `--condition` which would allow arabitrary python expressions to be evaluated. Here's an example use case:

    for node in fmf.Tree(path).climb():
        if node.get(['execute', 'how']) == "dependency":
            print(node.get(['execute', 'components']))

In order to filter only metadata nodes with the `dependency` implementation of the `execute` step it's necessary to access second level of the dictionary which is not possible using `--filter` option. Together with `--format` this would allow much more flexibility right from the command line.

**Comment by jscotka** [comment]
It is possible to do via my PR: https://github.com/psss/fmf/pull/56

example:
```
fmf show --path examples/advance_filtes/ --advanced_filter "execute['how']=='dependency'"
/top/rhel7
execute: {'how': 'dependency'}
release: 7.1
tags: default
```

**Comment by psss** [comment]
Thanks for the patch, Honzo!
