### ISSUE TITLE
fmf doesn't accept the yaml standard for documents (`---`)

### ISSUE THREAD

**Issue by TomasTomecek** [psss/fmf#64]
I just created an fmf file like this:
```yaml
---
/tests/...
```

The problem is that fmf tool couldn't handle the three leading dashes which are a common way to start a yaml document: https://stackoverflow.com/questions/50788277/why-3-dashes-hyphen-in-yaml-file

**Comment by psss** [comment]
Weird. This should be supported. I'm using `yaml` module to handle yaml parsing. Quick test works for me as well:

    > find
    .
    ./tests.fmf
    ./.fmf
    ./.fmf/version

    > cat tests.fmf
    ---
    /smoke:
        summary: Simple smoke test
        test: fmf --help

    > fmf show
    /tests/smoke
    summary: Simple smoke test
    test: fmf --help

Could you provide your full fmf file?

**Comment by TomasTomecek** [comment]
hm, can't reproduce any more

I feel like the problem was that I put the fmf file inside .fmf/ dir -- that was the real problem why fmf tool couldn't find my metadata

**Comment by psss** [comment]
Yes, the `.fmf` directory is special and is ignored when exploring available metadata.
