### ISSUE TITLE
RFE add option to print absolute paths to found tests

### ISSUE THREAD

**Issue by hegerj** [psss/fmf#7]
Currently when searching for tests fmf returns relative paths:

\# fmf /root/tests/ --brief --key test --filter component:libselinux
tests/upstream-tests/selinux/libselinux/setenforce
tests/upstream-tests/selinux/libselinux/getsebool

What I would like to see would be absolute paths:

\# fmf /root/tests/ --brief --key test --filter component:libselinux --absolute_path
/root/tests/upstream-tests/selinux/libselinux/setenforce
/root/tests/upstream-tests/selinux/libselinux/getsebool

**Comment by jscotka** [comment]
this has to be solved very carefully. as discussed with @psss , this is very connected with virtual testcases, what has another location of self itself and what ``test:`` key means,
for this purpose this is connected with beaker, that there is directory and you don't care that in ``test:`` key there is for examle ``./runtest.sh`` or ``make run`` what will do the same.
but in case there should be something usefull  than just non-emty string, close to ``true`` value

**Comment by jscotka** [comment]
partially solved by: https://github.com/psss/fmf/pull/16

**Comment by psss** [comment]
Yes, we need to make very clear how the path will be detected and how tests will be executed. There's is an initial draft of the proposed attributes on the Fedora wiki:

https://fedoraproject.org/wiki/CI/Metadata

Anyway, I think the new `--format` feature should probably cover this use case. See examples:

http://fmf.readthedocs.io/en/devel/examples.html#format

What do you think, Jakub?

**Comment by jscotka** [comment]
the best solution could be: add this new prefix, what leads to ivoked test (dirname + basename) https://github.com/psss/fmf/pull/19  with this format feature

**Comment by psss** [comment]
Using the new `--format` option together with the Tree.root attribute this can be done:

    > fmf examples/wget/ --key test --format '{}/{}/{}\n' \
      --value 'root' --value 'data.get("path") or name' --value 'data["test"]'

Path can be used to specify directory if it differs from the object name:

    description: Check recursive download options
    tags: [Tier2]
    test: runtest.sh
    path: wget/recursion

The results looks like this:

    /home/psss/git/fmf/examples/wget/download/test/runtest.sh
    /home/psss/git/fmf/examples/wget/recursion/runtest.sh
    /home/psss/git/fmf/examples/wget/recursion/runtest.sh
    /home/psss/git/fmf/examples/wget/protocols/ftp/runtest.sh
    /home/psss/git/fmf/examples/wget/protocols/http/runtest.sh
    /home/psss/git/fmf/examples/wget/protocols/https/runtest.sh

Closing as this general solution should cover the requested use case.
