### ISSUE TITLE
Matching distro against a context with distro name only

### ISSUE THREAD

**Issue by psss** [psss/fmf#89]
If there is no distro version specified in the context, comparing against distro specific version gives `False`:

    >>> import fmf
    >>> fmf.context.Context(distro='fedora').matches('distro < fedora-33')
    False

@lukaszachy, shouldn't this raise a `CannotDecide` exception instead?

**Comment by lukaszachy** [comment]
No, you asked for '<' not for '~<'. It works as expected.

**Comment by lukaszachy** [comment]
There are no special dimensions, we have just added special operand which enforces same minor version.

One would expect following, right?
```
>>> fmf.context.Context(distro='fedora-33').matches('distro == fedora')
True
```

I guess we will not break anything if in comparison we require both sides to have non-empty version parts so
`foo > foo-1` as well as `foo > bar` is `CannotDecide` but `foo-1 > foo-0.8`

**Comment by lukaszachy** [comment]
How about `foo >= foo-1` ? Since  `foo == foo-1` is True we need to have `foo >= foo-1`  True as well, IMHO

**Comment by psss** [comment]
What about requiring context (left side) to have version defined if rule (right side) uses it?

context operator rule  | result
-----------------------|----------
fedora-33 == fedora    | True
fedora-33 >= fedora-32 | True
fedora == fedora       | True
fedora >= centos       | True (string comparison)
fedora == fedora-33    | CannotDecide
fedora >= fedora-33    | CannotDecide

**Comment by lukaszachy** [comment]
I think I need to adjust how comparing works (again) - in addition to have version part filled, ContextValue will need to have same name parts. 

Because now you can't really compare module streams.
This matches because of string compare between module names
```python
>>> Context("module = py:5.28").matches("module > perl:5.28")                                                                                      
True
```
If you use minor mode comparison it is skips compare as one expect but you loose ability to version compare streams between major (here perl:6 to perl:5) which you are likely to need...
```python
>>> Context("module = py:5.28").matches("module ~> perl:5.28")                                                                                      
CannotDecide:
>>> Context("module = perl:6.28").matches("module ~> perl:5.28")
CannotDecide:
```

So the proposal is to allow comparing only if both sides have same name, so following will be possible
```python
>>> Context("module = perl:6.28").matches("module > perl:5.28")
True
>>> Context("module = py:5").matches("module > perl:5.28")
CannotDecide:
>>> Context("module = py:5").matches("module >= perl:5.28")
CannotDecide:
```

**Comment by lukaszachy** [comment]
From IRC:
`rhel-7 == rhel-7.3 == rhel-7.3.eus` thus `rhel-7 >= rhel-7.3 >= rhel-7.3.eus`
But if you need strict check for minor version you need to use `<, ~<, >, ~>` e.g.
`rhel-7 > rhel-7.3 ---> CannotDecide`

**Comment by martinky82** [comment]
I would argue against 

fedora >= centos | True (string comparison)

I reckon, there is no way to tell which one actually is higher / newer / whatever. Comparing different distros does not make much sence. The resolution in this case should be: CannotDecide

**Comment by lukaszachy** [comment]
> fedora >= centos | True (string comparison)
> I reckon, there is no way to tell which one actually is higher / newer / whatever. Comparing different distros does not make much sence. The resolution in this case should be: CannotDecide

Yes, it will be CannotDecide
